demo1/demo1/demo1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('newyear/', include('newyear.urls')),
    path('tasks/', include('tasks.urls')),
    path('admin/', admin.site.urls),
]

demo1/demo1/newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

demo1/demo1/polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('nick', views.nick, name='nick'),
    path('helen', views.helen, name='helen'),
    path('<str:name>', views.greet, name='greet'),
]

demo1/demo1/tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add, name='add'),
]

demo1/demo1/newyear/models.py
from django.db import models

# Create your models here.

demo1/demo1/polls/models.py
from django.db import models

# Create your models here.

demo1/demo1/tasks/models.py
from django.db import models

# Create your models here.

demo1/demo1/newyear/views.py
from django.shortcuts import render

# Create your views here.

import datetime

def index(request):
    now = datetime.datetime.now()
    return render(request, 'newyear/index.html', {
        'newyear': now.month == 1 and now.day == 1
    })

demo1/demo1/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    # return HttpResponse("<h2 style='color:blue'; font-family='sans-serif'>Hello, World!</h2>")
    return render(request, 'hello/index.html')
   
def nick(request):
    return HttpResponse("<h2 style='color:blue'; font-family='sans-serif'>Hello, Nick!</h2>")
    
def helen(request):
    return HttpResponse("<h2 style='color:blue'; font-family='sans-serif'>Hello, Helen!</h2>")

def greet(request, name):
    # return HttpResponse(f"<h2 style='color:blue'; font-family='sans-serif'>Hello, {name.capitalize()}!</h2>")
    return render(request, 'polls/greet.html', {'name': name.capitalize()})

demo1/demo1/tasks/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse


class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
#    priority = forms.IntegerField(label="Priority",
#                   min_value=1, max_value=10)

    

# Create your views here.

tasks = []

def index(request):
    return render(request, 'tasks/index.html', {
        'tasks': tasks
    })

def add(request):
    if request.method == 'POST':
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data['task']
            tasks.append(task)
            return HttpResponseRedirect(reverse('tasks:index'))
        else:
            return render(request, 'tasks/add.html', {
                'form': form
            })

    return render(request, 'tasks/add.html', {
        'form': NewTaskForm()
    })

demo1/demo1/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Is it New Year's?</title>
	<link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
  </head>
  <body>
    {% if newyear %}
	  <h1>YES</h1>
	{% else %}
	  <h1>NO</h1>
	{% endif %}
  </body>
</html>

demo1/demo1/polls/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Hello!</title>
  </head>
  <body>
	<h1>Hello, World!</h1>
  <body>
</html>

demo1/demo1/polls/templates/polls/greet.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Hello!</title>
  </head>
  <body>
	<h1>Hello, {{ name }}!</h1>
  </body>
</html>

demo1/demo1/tasks/templates/layout.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <title>Tasks</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

demo1/demo1/tasks/templates/tasks/add - Copy.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <title>Tasks</title>
    </head>
    <body>
        <h1>Add Task</h1>
        <form>
            <input type='text' name='task'>
            <input type='submit'>
        </form>
    </body>
</html>

demo1/demo1/tasks/templates/tasks/add.html
{% extends "layout.html" %}

{% block body %}
    <h1>Add Task</h1>
	<form action="{% url 'tasks:add' %}" method='post'>
		{% csrf_token %}
        <!-- <input type='text' name='task'> -->
		{{ form }}
        <input type='submit'>
    </form>
	<a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

demo1/demo1/tasks/templates/tasks/index - Copy.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <title>Tasks</title>
    </head>
    <body>
        <ul>
            {% for task in tasks %}
                <li>{{ task }}</li>
            {% endfor %}
        </ul>
	</body>
</html>

demo1/demo1/tasks/templates/tasks/index.html
{% extends "layout.html" %}

{% block body %}
    <h1>Tasks</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% endfor %}
    </ul>
	<a href="{% url 'tasks:add' %}">Add a New Task</a>
{% endblock %}